### ISSUE TITLE
Loss is zero

### ISSUE THREAD

**Issue by kikirizki** [Wendison/VQMIVC#16]
Hi Thank you for your great work, recently I train this VQMIVC to jvs dataset. But I got strange loss value please look at this :
`epoch:506, global step:201, recon loss:3.645, cpc loss:2.398, vq loss:0.000, perpexlity:1.000, lld cs loss:31.000, mi cs loss:0.000E+00, lld ps loss:0.271, mi ps loss:-0.000, lld cp loss:-63.999, mi cp loss:0.000, used time:0.396s
`
is that normal that some loss turn into zero?

**Comment by Wendison** [comment]
Hi, in my cases, the mutual information losses were around 0, but not equal to 0. I notice that the perplexity is 1.0, which means only one element in the codebook is used, so the codebook is not well trained. Based on my experience, this is most likely caused by the poor estimation of mutual information and log-likelihood, one way to alleviate this issue is to change the hyperparameters of the CLUB-network, e.g., increase/decrease the hidden layers' dimension or change the mutual information loss weight, it depends on the dataset you used, so they need to be carefully designed.

**Comment by kikirizki** [comment]
@Wendison Oh thank you for your brief response. I will try it
