### ISSUE TITLE
Improper converted audio when source = reference

### ISSUE THREAD

**Issue by vishalbhavani** [Wendison/VQMIVC#5]
Hi,
I tried using `python convert_example.py -s test_wavs/jane3.wav -r test_wavs/jane3.wav -c converted -m checkpoints/useCSMITrue_useCPMITrue_usePSMITrue_useAmpTrue/VQMIVC-model.ckpt-500.pt` to check out how the results are when source audio and reference audio are same. But the output is mostly silent. Am I missing something? To reproduce the results, the audio files and vocoder are uploaded [here](https://drive.google.com/drive/folders/1bAvh_ImwN-i6hBPTdydAi2SMz5Sl8Mgn?usp=sharing)

Source and reference: https://drive.google.com/file/d/1bPAQ9UaKJF1gNNCtkeDmySxLv_uXW1HN/view?usp=sharing
Converted: https://drive.google.com/file/d/1TmxjpHx3WY3nKRwy5lz04LWfKAo69qwW/view?usp=sharing
CC: @Wendison

**Comment by Wendison** [comment]
Hi, thanks for your interests. I have run your example and can obtain similar results. I think this is caused by the domain mismatch between your wav (jane3.wav) and the wavs (from VCTK dataset) used for training the VC model, the mismatch may arise from the channel, volume, recording environment etc. If you increase the volume of your wav before computing mel-spectrograms, e.g., wav = wav/max(abs(wav))*0.9, intelligible speech can be obtained though the content is not maintained well enough. I think one way that may solve this issue is to use more diverse data for training to increase the generalization ability of the VC model.

**Comment by vishalbhavani** [comment]
Thanks, @Wendison. I have 15 minutes of speech recording for each of the source and target speakers and I want to train a voice conversion model for that specific pair.
1) Can I create a dataset in the same structure as the vctk dataset and train the model? Is there anything else I need to change apart from the dataset?
2) Is 15 mins of data enough for doing this?

**Comment by Wendison** [comment]
@vishalbhavani Hi, for your questions:
1. Yes, you can create the same structure as VCTK. You may try to combine your data with VCTK for training VQMIVC, more data is helpful to enhance VC performance;
2. If you combine 15mins of data with VCTK, I think that's enough; However, if you only use 15mins of data for training, I think the resulting VC may not perform well as it is prone to overfiting.
