### ISSUE TITLE
Question About the Embedding

### ISSUE THREAD

**Issue by mizunonakama** [Wendison/VQMIVC#9]
Hi, I have a question about a configuration parameter called _encoder_lf0_type_ = 'no_emb'.

![image](https://user-images.githubusercontent.com/61395538/134348284-b2d54b59-8f54-45c1-b21d-351bcf6a5828.png)

I'm training  the model with a subset of 13 speakers, which 4 of them aren't from the dataset, I let it run for 500 epochs but the results with some of those speakers aren't as good as in the paper. Probably it is due to the small amount of speakers used for training, but I gotta ask: 

1. What does the encoder_lf0_type parameter is about?
2. Can you give me some advice on the training process? (min number of speakers for a decent result, number of epochs, etc)

Thank you.

**Comment by Wendison** [comment]
Hi, for your questions:
1. `encoder_lf0_type=no_emb` uses original values of F0 as inputs of decoder, else F0 embeddings are obtained via a CNN-LSTM network and used as inputs of decoder. Please see https://github.com/Wendison/VQMIVC/blob/ee325a98626ced19cbecc5d0ab57e89add04b76f/model_encoder.py#L28-L58 for more details. My experiments show that `encoder_lf0_type=no_emb` achieves better performance.
2. I haven't tried low-resource settings, so I can't tell you the exact min number of speakers. Since this work aims to achieve one-shot (or any-to-any) VC, more training speakers lead to better results for out-of-domain speakers that are not seen during training. However, if you only want to perform VC across training speakers, I think you need to reduce the parameters of networks, e.g., decrease dimension of layers, and reduce the training epochs to avoid overfitting, and you can listen to intermediate converted results during the training process to determine the best epochs used for training. Good luck :)
